name: mak_life_dairy_fresh
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  # flutter_download_manager: ^0.5.5
  flutter_downloader: ^1.11.8
  flutter_inappwebview: ^6.1.5
  geolocator: ^13.0.2
  get: ^4.6.6
  # get_storage: ^2.1.1
  http: ^1.2.2
  intl: ^0.20.1
  open_filex: ^4.5.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
